version: '2'

services: 
    main:
        build: ./pythonapi
        ports:
            - "5052:5052"
        network_mode: host
        volumes:
            - /home/deadly/testLi-Vol:/vol
    nginx:
        build: ./nginx
        container_name: nginx
        environment: 
            - SERVER_NAME=0.0.0.0
        restart: always
        network_mode: host
